<?php

require_once CONTEXT_ROOT . '/Context/Settings/Settings.inc';
require_once CONTEXT_ROOT . '/Context/Router/Router.inc';
require_once CONTEXT_ROOT . '/Context/Session/SessionPHP.inc';
require_once CONTEXT_ROOT . '/Context/Database/Database.inc';
require_once CONTEXT_ROOT . '/Context/Context/Context.inc';
require_once CONTEXT_ROOT . '/Controllers/Controller.inc';
require_once CONTEXT_ROOT . '/Models/Organizer.inc';